POST https://crud-node-0f45.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

GET https://crud-node-0f45.onrender.com/videos

###

PUT https://crud-node-0f45.onrender.com/videos/ae589fcf-651d-443d-939f-cfbae04902c3
Content-Type: application/json

{
  "title": "Video node5555",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

DELETE https://crud-node-0f45.onrender.com/videos/ae589fcf-651d-443d-939f-cfbae04902c3