POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/8d052c3f-4aaf-461e-a3e4-09c6f1406cdd
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/8d052c3f-4aaf-461e-a3e4-09c6f1406cdd